channels:
  - conda-forge
  - bioconda
dependencies:
  - python==3.11.10
  - nest-asyncio==1.6.0
  - numpy==1.26.4
  - requests==2.32.3
  - scipy==1.14.0
  - pip
  - pip:
    - matplotlib==3.9.0
    - opencv-python==4.10.0.84
    - pynput
    - python-dotenv
    - python-socketio==5.11.3
    - uvicorn[standard]==0.30.1
    - websocket-client
    - websockets
    - wxPython==4.2.1
